### ISSUE TITLE
Best Practices and Guides - Update bug reporting in TFS 2010

### ISSUE THREAD

**Issue by matherrien92** [esdc-devcop/esdc-devcop.github.io#207]
Update to the current version of TFS. Update the screenshots. Review all the information to make sure it is still relevant to the new version of TFS/VS.

**Comment by j-paquette** [comment]
@matherrien92    
I don't know how to update this.   
The guide says these recommendations come from 

> a joint effort between developers and testers and is approved by the CS-03 Technical Advisors

I couldn't find information to confirm whether bug reporting is using ADO boards instead of the TFS-2010.
The only information I found was 1 item opened in our project in January: https://ado.intra.dmz/projectcollection/EWS-SWE/_workitems/edit/505161/   and a link to Microsoft documentation on how to manage bugs: https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/manage-bugs?view=azure-devops   
My suggestion:    
to remove the page.   
Once we get clear guidelines from the CS-03, testers about how they manage bug reporting we can add their details in a new page. What do you think?

**Comment by matherrien92** [comment]
ok I agree, let's remove it until we get a clear direction. For now, this page is not helpful anymore.
